#137090993/jasmine karma test for front end
andela/temari-cfh pull request #12
Opened 2017-01-11 12:01 UTC by andela-vnwosu

#### What does this PR do?
 Test the front end
#### Description of Task to be completed? 
To ensure the front end has all functionality work the way it was intended. We used Jasmine and Karma(with PhantomJS, Chrome and Firefox) to setup front end testing environment.

#### How should this be manually tested? 
run 'npm install' to install all dependencies in the package.json

2017-01-11 13:59 UTC, nyambati requested changes
The are a lot of HoundCI Issues and a merge conflict in your PR. Resolve this issues first.

You can resolve the merge conflicts by updating your branch with the latest code from `develop` branch.

2017-01-17 11:24 UTC, nyambati commented on karma.conf.js
> +    files: [
The `js` folder contains subfolders. What you have specified only picks files in the js folder but ignore the other folders `controllers` and `services`. Change your wildcards to cater for files the above named folders.
You have not also included the angular dependencies refer to this [article ](http://ericnish.io/blog/set-up-
jasmine-and-karma-for-angularjs/)and make the necessary changes.

2017-01-17 11:24 UTC, nyambati commented on karma.conf.js
> +        'spec/*.js',
Our Tests will reside in the test folder and therefore this should be changed to `test/client`. to separate backend and front-end tests.

2017-01-17 13:56 UTC, nyambati requested changes
Good Job 👍 . Clean up the git ignore and all should be good for the demo tomorrow.

2017-01-17 13:56 UTC, nyambati commented on .gitignore
> +<<<<<<< HEAD
You failed to clean this file, make sure all the merge conflict diff are removed

2017-01-17 14:11 UTC, andela-vnwosu commented on .gitignore
> +<<<<<<< HEAD
ok, thanks

2017-01-19 12:55 UTC, nyambati approved these changes

2017-01-19 12:56 UTC, merged