Chore/137090995/grunt to gulp
andela/temari-cfh pull request #15
Opened 2017-01-12 00:33 UTC by andela-oaboluwarin

**What does this PR do?**

Run repetitive tasks

**Description of Task to be completed?**

Create a gulpfile.js to act as the task runner in place of the existing gruntfile.js while taking note of the specifications in the gruntfile.

**How should this be manually tested?**

run 'gulp' to see that all specified tasks are running.

2017-01-13 07:45 UTC, nyambati commented on gulpfile.js
> +gulp.task('default', ['jshint', 'server', 'watch', 'sass']);
This task should be placed below all the tasks

2017-01-13 08:13 UTC, andela-oaboluwarin commented on gulpfile.js
> +gulp.task('default', ['jshint', 'server', 'watch', 'sass']);
Effected the change. Thank you. :)

2017-01-13 08:19 UTC, andela-oaboluwarin commented on gulpfile.js
> +        .pipe(gulp.dest('./public/lib/'))
Change effected

2017-01-16 16:13 UTC, nyambati requested changes

2017-01-16 16:13 UTC, nyambati commented on .travis.yml
> +  before_script:
There is a yam syntax error here. `before_script` and services should start from the same line
```yml
services:
  - mongodb
before_script:
```

2017-01-18 07:08 UTC, andela-oaboluwarin commented on .travis.yml
> +  before_script:
I made the changes you suggested here. Without the "before_script" however.

2017-01-21 13:19 UTC, nyambati approved these changes

2017-01-21 13:22 UTC, merged