#137091003/send invites to 11 other people
andela/temari-cfh pull request #24
Opened 2017-01-25 10:34 UTC by andela-mabdussalam

#### What does this PR do?
Allows users to be invite users.
#### Description of Task to be completed?
Users are able to invite up to 11 users
#### How should this be manually tested?
Test on heroku

2017-01-25 11:40 UTC, andela-mabdussalam commented on app/controllers/api/mailer.js
> +require('dotenv').config();
Repetitive code. Already exists in server.js

2017-01-25 11:43 UTC, andela-mabdussalam commented on app/controllers/api/mailer.js
> +      res.json({ status: 'error' });
Add descriptive error message.

2017-01-25 11:45 UTC, andela-mabdussalam commented on app/controllers/api/mailer.js
> +      res.json({ status: 'error' });
Also use return to avoid an "else" statement

2017-01-25 11:46 UTC, andela-mabdussalam commented on app/controllers/api/search.js
> + const User = mongoose.model('User');
Ensure proper indentation

2017-01-25 11:50 UTC, andela-mabdussalam commented on app/controllers/api/search.js
> +   if (req.user && req.user._id) {
Remove logic from if statement.

2017-01-25 11:52 UTC, andela-mabdussalam commented on app/controllers/api/search.js
> +           return res.status(404).send('No data found');
Send consistent error messages.

2017-01-25 11:54 UTC, andela-mabdussalam commented on config/env/all.js
> +  db: process.env.MONGOHQ_URL || 'mongodb://localhost:27017/cfh',
remove or conditions.

2017-01-25 11:56 UTC, andela-mabdussalam commented on config/routes.js
>    var authn = require('../app/controllers/userAuth');
Change to userAuth and replace var with const.

2017-01-30 00:28 UTC, nyambati requested changes
You codebase has some few things that need your attention. These include indentation, Angular best practices, Proper use of conditionals. I have made a couple of comments, make the relevant changes

2017-01-30 00:28 UTC, nyambati commented on public/js/controllers/game.js
> +      $http({
Abstract this functionality to services. Controllers should not be used to make `http` requests rather only to bind data to the Scope.

2017-01-30 00:28 UTC, nyambati commented on public/js/controllers/game.js
> +    $http.get(`/api/search/users/${$scope.email}`)
This part should be abstracted to Angular services as well.

2017-01-30 00:28 UTC, nyambati commented on public/js/directives.js
> +  .directive('invitelist', function() {
Directives should be named in camelCase. A good name for this should have been `inviteList`. And can be used in the UI as `<invite-list></invite-list>
`

2017-02-03 17:50 UTC, nyambati approved these changes

2017-02-06 18:15 UTC, merged