Chore/137256077/deploy app to heroku
andela/temari-cfh pull request #7
Opened 2017-01-10 08:16 UTC by andela-ooyeniran

2017-01-10 14:15 UTC, q-ode commented on config/env/all.js
> +    db: process.env.MONGOHQ_URL || 'mongodb://localhost:27017'
What are you trying to achieve with this: `|| 'mongodb://localhost:27017'`?

2017-01-10 16:02 UTC, andela-ooyeniran commented
I assigned/specified a port for it to run locally on my computer, am I suppose to take it out when I deploy?
> On 10 Jan 2017, at 3:15 PM, Adebayo Adesanya <notifications@github.com> wrote:
> 
> @q-ode commented on this pull request.
> 
> In config/env/all.js <https://github.com/andela/temari-cfh/pull/7#pullrequestreview-15922458>:
> 
> > @@ -5,5 +5,5 @@ var keys = rootPath + '/keys.txt';
>  module.exports = {
>  	root: rootPath,
>  	port: process.env.PORT || 3000,
> -    db: process.env.MONGOHQ_URL
> +    db: process.env.MONGOHQ_URL || 'mongodb://localhost:27017'
> What are you trying to achieve with this: || 'mongodb://localhost:27017'?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/andela/temari-cfh/pull/7#pullrequestreview-15922458>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AXyFg45kmIR3jIV7lFLVIGrsNbNSWjWUks5rQ5JpgaJpZM4LfIxq>.
>

2017-01-11 06:50 UTC, andela-ooyeniran commented on config/env/all.js
> +    db: process.env.MONGOHQ_URL || 'mongodb://localhost:27017'
I assigned/specified a port for it to run locally on my computer, am I suppose to take it out when I deploy?

2017-01-11 12:33 UTC, q-ode commented on config/env/all.js
> +    db: process.env.MONGOHQ_URL || 'mongodb://localhost:27017'
What I see you're doing is specifying the MongoDB URL for the database as `mongodb://localhost:27017` if it doesn't exist in the environment variables.

I think you could specify this URL in the `MONGOHQ_URL` environment variable for this project.

Checkout the `dotenv` module.

2017-01-11 13:15 UTC, andela-ooyeniran commented on config/env/all.js
> +    db: process.env.MONGOHQ_URL || 'mongodb://localhost:27017'
ok thanks

2017-01-11 14:26 UTC, nyambati requested changes
Follow this guide to configure a correct deployment to Heroku and make the necessary changes required for a successful automated deploy.

https://docs.travis-ci.com/user/deployment/heroku/

2017-01-11 14:26 UTC, nyambati commented on app/views/includes/foot.jade
> +script(type='text/javascript', src='https://code.angularjs.org/1.1.5/angular.js')
These files should be downloaded using bower instead of using CDN

2017-01-16 12:28 UTC, nyambati approved these changes

2017-01-16 12:28 UTC, merged